swagger: '2.0'
info:
  title: Web API Skeleton
  description: Skeleton for Dropwizard Web APIs
  version: '0.0'
  license:
    name: GNU Affero General Public License Version 3
    url: http://www.gnu.org/licenses/agpl-3.0.en.html
externalDocs:
  description: GitHub Repository
  url: https://github.com/osu-mist/web-api-skeleton
host: localhost
schemes:
  - http
basePath: /api/v0
consumes:
  - text/plain
produces:
  - text/plain
paths:
  /:
    get:
      summary: Get information
      description: Build and runtime information about the application.
      responses:
        200:
          description: Object containing information
          schema:
            $ref: '#/definitions/Info'
definitions:
  Info:
    properties:
      name:
        type: string
      time:
        type: integer
      commit:
        type: string
      documentation:
        type: string
  Error:
    properties:
      status:
        type: integer
      developerMessage:
        type: string
      userMesage:
        type: string
      code:
        type: integer
      details:
        type: string
